import { execFileSync } from "node:child_process"
import { readFileSync, statSync } from "node:fs"

// Two rules, both enforced here rather than trusted to habit: no dashes that a
// keyboard does not produce, and no tool attribution anywhere in the tracked
// tree. The history is part of what this repository ships.
const BANNED: ReadonlyArray<readonly [string, RegExp]> = [
  ["em-dash", /—/],
  ["en-dash", /–/],
  ["tool attribution", /\b(claude|copilot|chatgpt|codex|cursor\.sh)\b/i],
  ["generated-by claim", /generated by ai|ai-assisted|written by ai|co-authored-by: *\w/i],
]

// Recorded fixtures and published evidence carry text from real Figma files,
// which this repository does not get to edit.
const SKIP = /^(LICENSE|package-lock\.json|fixtures\/|evidence\/|dist\/|script\/check-prose\.ts$)/

const tracked = execFileSync("git", ["ls-files"], { encoding: "utf8" }).split("\n").filter(Boolean)

const failures: string[] = []

for (const file of tracked) {
  if (SKIP.test(file)) continue
  if (!statSync(file, { throwIfNoEntry: false })?.isFile()) continue

  const contents = readFileSync(file)
  if (contents.subarray(0, 8000).includes(0)) continue

  contents
    .toString("utf8")
    .split("\n")
    .forEach((line, index) => {
      for (const [label, pattern] of BANNED) {
        if (pattern.test(line)) failures.push(`${file}:${index + 1}: ${label}: ${line.trim()}`)
      }
    })
}

if (failures.length === 0) {
  console.log(`prose ok, ${tracked.length} tracked files`)
  process.exit(0)
}

console.error(failures.join("\n"))
console.error(`\n${failures.length} prose violation(s)`)
process.exit(1)
